version: "3.8"
services:
  api:
    build: .
    container_name: fastapi-tutorial1
    ports:
      - 8000:80
    volumes:
      - ./api:/api
      - ./upload-images/:/upload-images/user/
    env_file:
      - ./api/.env